export const SET_LEAGUEID = 'MATCH/SET_LEAGUEID'
export const GET_COUNTRIES = 'GET_COUNTRIES'
export const GET_SEASONS = 'GET_SEASONS'
export const GET_RESULTS = 'GET_RESULTS'
export const SET_FIXTURE_DETAILS = 'DETAILS/SET_FIXTURE_DETAILS'
export const SET_DETAILS = "DETAILS/SET_DETAILS"
export const SET_FIXTURE_ID = 'DETAILS/SET_FIXTURE_ID'